[plugin]
repository = "https://github.com/NukoOoOoOoO/GoodMemoryCN.git"
commit = "0709589862ad8dadbd3d204f5afec875b405973e"
owners = [
    "ascclemens",
    "VergilGao"
    "NukoOoOoOoO",
]
project_path = "GoodMemory"
changelog = "api7"
version = "1.1.2.0"
