[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "7f1dca7734ff5652fb33525e9d90d0e654c9aa4d"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 将 玩家搜索 添加回来
- 修复实际行为与描述不一致
"""
