[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "cca4a2515938bc8a7ec942ff90ffaadce352c357"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 可能损坏已有数据，请注意备份
- 有限支持7.0
- 命令`/pname update`暂时不可用
"""
