[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "8bd826c059b7a75969cb92481644054ab2200104"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 支持api8
- 推送更新
"""
