[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "f86f7993eddf989653798d6e3b154151c75ae23d"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 兼容国服6.4
- 修复错误初始化
"""
