[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "026667da47d5352ae6d3dea80af759d500367f3e"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 非游戏好友名单中的玩家具备更新的能力
- 添加一个临时订阅列表以将非关联玩家追加到插件的名单中
- 取消"玩家搜索"更新的功能
- 添加从部队成员更新的功能
- 提升文本质量
"""
