[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "8309a9c94b69eab4911be29dc8016a3ec6e86955"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 修复PlayerEntry结构改变，导致网络包失效问题。现在可以正常自动更新数据
"""
