[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "ff3dac48f421082a5419e51062a4b339dd94fa6b"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 修复.Net6兼容性问题
"""
