[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "a212c0719c5a344e2086fcf63d7527d7f392474d"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 插件描述小提升
- 修复更换卫月位置后，无法正常读取数据问题
"""
