[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "8786e4bdb690bf62c4f1faf99dfb57adec74c620"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 修复.Net6兼容性问题
"""
