[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "72a258637257e80e1defa52e50822d7935bbcb03"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 修复有时UI崩溃的问题
- 修复右键添加昵称失败
"""
