[plugin]
repository = "https://github.com/Yarukon/Accountant.git"
commit = "08abac60d10e770791c98eaeb26c73dde0a13665"
owners = [
    "Ottermandias",
    "Yarukon"
]
project_path = "Accountant"
changelog = "Updated for Dalamud staging."
