[plugin]
repository = "https://github.com/wozaiha/xivPartyIcons.git"
commit = "6b1d5a049ab52d4765a40c13d28376a6cc38c2d1"
owners = [
    "shdwp",
    "avafloww",
    "squidmade",
    "wozaiha",
]
project_path = "PartyIcons"
changelog = """
- Added the following icons as priority icons:
  - Looking to Meld Materia
  - Looking for Party
  - Game Master
  - Game QA
  - Event Participant
- I plan to go through and just add all of the overworld player icons (with exceptions as needed) since that'd be easier than adding them gradually as requested.
"""
