[plugin]
repository = "https://github.com/wozaiha/xivPartyIcons.git"
commit = "4b8432a88e45aa243f4933e37094b9b27831abc7"
owners = [
    "shdwp",
    "avafloww",
    "squidmade",
    "wozaiha",
]
project_path = "PartyIcons"
changelog = """
- Changed the display name of the plugin to improve discoverability.
- Fixed errors in log when in hunt train as SCH or SMN with pet out.
"""
