[plugin]
repository = "https://github.com/wozaiha/VisibilityPlugin.git"
commit = "4a7dafdd139383fb8b5e51557bcac651326b825f"
owners = ["SheepGoMeh","wozaiha"]
project_path = "Visibility"
changelog = "Vis刷新BUG修正."
