[plugin]
repository = "https://github.com/wozaiha/VisibilityPlugin.git"
owners = [ "SheepGoMeh",]
project_path = "Visibility"
commit = "088e44b903f81757e9dbadb43438efa1ba4c039f"
changelog = "请尽量使用UI添加角色，如实在需要使用命令行添加黑白名单，请在角色名前额外敲个空格"
