[plugin]
repository = "https://github.com/wozaiha/VisibilityPlugin.git"
owners = [ "SheepGoMeh",]
project_path = "Visibility"
commit = "341d5e5b79207f292111200cbcab2ba7e24f229c"
changelog = "- 国服6.4适配"
