[plugin]
repository = 'https://github.com/tssailzz8/GlamaholicForCN.git'
commit = 'ab8327cae90aae68247a5cb9b243341734cca54f'
owners = [ 'ascclemens', 'tssailzz8' ]
changelog = 'The Glamour Dresser has 800 slots now! Accounted for that and fixed the problems arising because of that.'
