[plugin]
repository = 'https://github.com/tssailzz8/GlamaholicForCN.git'
commit = '3e8ebcb836c765c9fe849db9162442306ffc85b2'
owners = [ 'ascclemens', 'tssailzz8' ]
changelog = 'The Glamour Dresser has 800 slots now! Accounted for that and fixed the problems arising because of that.'
