[plugin]
repository = "https://github.com/k99k5/IslandWorkshopSolver.git"
commit = "7f3a22ba41fe67240b7f289feae26cea32f396a7"
owners = [
    "rosella500",
    "k99k5"
]
project_path = "Beachcomber"
changelog = "增加汉化"
