[plugin]
repository = "https://github.com/k99k5/IslandWorkshopSolver.git"
commit = "c60099bc6c643ca4c2f1d5048425ae08596cc021"
owners = [
    "rosella500",
    "k99k5"
]
project_path = "Beachcomber"
changelog = "增加汉化"
