[plugin]
repository = "https://github.com/ShadyWhite/SubmarineTracker.git"
commit = "061fad233c64190a74e7584ecdc22cfcf9599d38"
owners = ["Infiziert90", "ShadyWhite"]
project_path = "SubmarineTracker"
