[plugin]
repository = "https://github.com/Loskh/PingPlugin.git"
commit = "ec268f05cf8229b13df641eef49b47d8de7eb373"
owners = ["karashiiro"]
changelog = """\
- Fix ping sometimes getting stuck at 0ms (thanks Diyagi!)
"""
