[plugin]
repository = "https://github.com/wozaiha/PingPlugin.git"
commit = "6e6ed21f91a203f9a4fde0bfe0bea48e229796f6"
owners = ["karashiiro","wozaiha"]
changelog = """\
- Fixed server bar display failing to set up sometimes
"""
