[plugin]
repository = "https://github.com/MapleRecall/PixelPerfect.git"
commit = "cdd79e7d99a29a1540e65521f7acacd36b8a1de4"
owners = ["Haplo064"]
changelog = "Add an option for cutscene. Translate to 中文（简体）"
