[plugin]
repository = "https://github.com/lzt9746/mp-tick-bar.git"
commit = "04546e23aaa17fc69852b51706db8de45aa3fbd7"
owners = ["marconsou","lzt9746"]
project_path = "MPTickBar"
changelog = """Version 1.4.1.5
- 适配国服
"""
