[plugin]
repository = "https://github.com/Yarukon/xivr-cn.git"
commit = "fe0c568271c3e0f70294769b6a92f23e522e9afe"
owners = ["solimproper", "ProjectMimer", "Yarukon", "Bluefissure"]
project_path = "xivr"
changelog = "Testing for CN client"

[build]
image = "extended"

[[build.needs]]
type = "file"
url = "https://github.com/ValveSoftware/openvr/archive/refs/tags/v1.23.7.zip"
dest = "openvr.zip"
sha512 = "d6d9650cd801940c083649b7875b51e8cf55b6989850a7493784fea17449565a6ba84c19a6185ff3c15bc8d37c190c9c03f78d451ac81331bf80f90f1f41a826"
