[plugin]
repository = 'https://github.com/MapleRecall/OrangeGuidanceTomestone.git'
commit = '0be69591716ae3fa5d2186c23f631a253c8f66f4'
owners = [ 'ascclemens', 'MapleRecall' ]
project_path = 'client'
changelog = """\
- CN for FFXIV Pack
"""
