[plugin]
repository = 'https://github.com/MapleRecall/OrangeGuidanceTomestone.git'
commit = 'd1cf8a4fdb7ac7877a5a13d0827631798b082ad8'
owners = [ 'ascclemens', 'MapleRecall' ]
project_path = 'client'
changelog = """\
- CN for FFXIV Pack
"""
