[plugin]
repository = "https://gitlab.com/Bakura/casexile.git"
commit = "b1173cd721d0fa9eb5635814ce9a472d0ed1a799"
owners = ["RyouBakura", "AtmoOmen"]
project_path = ""
changelog = "Compatibility for API 9 / 6.5"
