[plugin]
repository = "https://github.com/VeroFess/ffxiv-priceinsight-cn.git"
commit = "d0f05df1cd0506d3793171a19f94a6cfd9e065a1"
owners = ["Kouzukii","VeroFess"]
project_path = ""
changelog = """
- 升级到 API 9
- 迁移 CDN 到企业线路
- 将国外查询直接重定向到源站
"""