[plugin]
repository = "https://github.com/VeroFess/ffxiv-priceinsight-cn.git"
commit = "9bfd57e621bc80d0efb242417e8aa4fe3340ac16"
owners = ["Kouzukii","VeroFess"]
project_path = ""
changelog = """
- 合并上游更新并翻译
"""