[plugin]
repository = "https://github.com/wozaiha/VisibilityPlugin.git"
owners = [ "SheepGoMeh",]
project_path = "Visibility"
commit = "997141ce1f6d8dd1574188009449f622012c32f8"
changelog = "6.5test"
