[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "8823d335bc82d9d473f9820e0db0a9e5200af64d"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = "- 请查阅GitHub更新日志页面"
