[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "f98d8ed47827fd35be6e1ba1632dcc1842a62cac"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = "- 请查阅GitHub更新日志页面"
