[plugin]
repository = "https://github.com/AtmoOmen/BetterPlaytime.git"
commit = "03d49d5d3b3793b3cd9a9db73d73b83f6a2d65f7"
owners = [
    "Infiziert90",
    "LittleNightmare",
    "AtmoOmen"
]
project_path = "BetterPlaytime"
