[plugin]
repository = "https://github.com/AtmoOmen/BetterPlaytime.git"
commit = "db5ef2e5150b66af7c4e481e2ab32fe32d4b44e0"
owners = [
    "Infiziert90",
    "LittleNightmare",
    "AtmoOmen"
]
project_path = "BetterPlaytime"
