[plugin]
repository = "https://github.com/wozaiha/ARealmRecorded.git"
commit = "411cc40d62f02e2edea634d6c576f2aac6238628"
owners = [ "UnknownX7" ]
changelog = '''
- Fixed for Dawntrail
- Added waymark toggle persistence'''
