[plugin]
repository = "https://github.com/LittleNightmare/Hunty.git"
commit = "c34ad05422bb245ebb30734d740036737c0ec2c9"
owners = [
    "Infiziert90",
    "LittleNightmare"
]
project_path = "Hunty"
changelog = """
- 修复极少数情况下无法传送的问题
- 修复错误的怪物坐标
"""
