[plugin]
repository = "https://github.com/LittleNightmare/Hunty.git"
commit = "3b1f69b21dd0401e12a2d32e3fa7e2592ce104d3"
owners = [
    "Infiziert90",
    "LittleNightmare"
]
project_path = "Hunty"
changelog = """
- 添加部分汉化
- 修复无法打开的问题
"""
