[plugin]
repository = "https://github.com/AtmoOmen/EurekaHelper.git"
commit = "8f2a2e4f0b2fa3b676cfcdf1adaf04756498ebc8"
owners = ["snooooowy", "AtmoOmen"]
project_path = "EurekaHelper"
changelog = """
Elemental Manager
- Added crowdsourced positions

Misc
- Updated contact information
"""
