[plugin]
repository = "https://github.com/imaginary-png/HuntHelper.git"
commit = "3335520cbac4beae7b0a30262cc51f45e8ae62b3"
owners = [
    "img02",
    "KirisameVanilla",
]
project_path = "HuntHelper"
