[plugin]
repository = "https://github.com/wozaiha/Distance.git"
commit = "d5792e81184509f72b73ad7a81df3358c446c7f8"
owners = [
    "PunishedPineapple",
    "MapleRecall",
    "wozaiha"
]
project_path = "Distance"
changelog = '''
- Reduce potential for log spamming.
'''