[plugin]
repository = "https://github.com/MapleRecall/Distance.git"
commit = "afdac1d9aeb78188799c5d52b29a835f62867e7c"
owners = [
    "PunishedPineapple",
    "MapleRecall"
]
project_path = "Distance"
changelog = '''
- Separated the aggro arc from the aggro distance readout.  Some options are still shared, but you can now set it to use one without the other.
- Made automatic updating of aggro data on by default *for new installations*.  If you have already loaded the plugin at least once, this change will have no effect.  Anyone can toggle the automatic update setting in the plugin configuration window at any time.
- Workaround for enemies with RSV'd names.
- Fixed some minor issues with the aggro data updater and improved logging.
- Improved the configuration window.
- Added a link to information about how distances work in the game.
'''
