[plugin]
repository = "https://github.com/MapleRecall/Distance.git"
commit = "6e62896c1dee8433301b2f9aa922af4b7f871340"
owners = [
    "PunishedPineapple",
    "MapleRecall"
]
project_path = "Distance"
changelog = '''
- 修复国服副本开怪距离显示
'''