[plugin]
repository = "https://github.com/MapleRecall/Distance.git"
commit = "ad9f61513f28b6e8809c896305366c7c653e67a5"
owners = [
    "PunishedPineapple",
    "MapleRecall"
]
project_path = "Distance"
changelog = '''
- 修复国服副本开怪距离显示
'''