[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "3137eadb239f4c62ca257672dfeac84237634e0c"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "修复特殊显示屏蔽词功能"
