[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "3b5f0871a8d886efd39917e1f1ca808dab693b23"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "Update API9"
