[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "acbf2dd771037074c10b8f4105c36e4f1b840160"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "支持招募板屏蔽词染色"
