[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "39d62cdbd87ae293cbbab97dbbcf1038c449bdd3"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "Update for CN 6.2"