[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "1c58c8a31b4a25b9c5a657bb0c963aa07cd5e9e9"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "支持更改染色范围"
