[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "c5b0a7dd579abcefab6d95d68ec9a5f8363868ea"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "Update for CN 6.2"