[plugin]
repository = "https://github.com/AtmoOmen/XIVLogger.git"
commit = "4cea1e9a2dc4c71f5a83a90de0b4f59f35b943dc"
owners = [
  "cadaeix",
  "Infiziert90",
  "AtmoOmen"
]
project_path = "XIVLogger"
