[plugin]
repository = "https://github.com/AtmoOmen/XIVLogger.git"
commit = "95a94a8d2edd7fe1df09b03285f0998b9827e5bc"
owners = [
  "cadaeix",
  "Infiziert90",
  "AtmoOmen"
]
project_path = "XIVLogger"
