[plugin]
repository = "https://github.com/tssailzz8/AutoMammet.git"
commit = "a2804faa117f523ba3ca780f932553a2357a576a"
owners = ["Rietty", "tssailzz8"]
project_path = "/AutoMammet"
changelog = "Updated some wording to be more clear where information is exported to."
