[plugin]
repository = "https://github.com/Bluefissure/EngageTimer.git"
commit = "a8466be2bf230159c680a014780f24d17a8d1ab8"
owners = ["xorus", "Bluefissure"]
changelog = """\
- Floating Window: the `:` separator in the stopwatch has gone back from their vacation"""
