[plugin]
repository = "https://github.com/wozaiha/EngageTimer.git"
commit = "da1a942be180edc545d8b176e28b806765e180fb"
owners = ["xorus","wozaiha"]
changelog = """\
- Fix decimals not being properly hidden with the display threshold option"""
