[plugin]
repository = "https://github.com/wozaiha/EngageTimer.git"
commit = "b7bdd29d79baae753b7a62bb96d01ffa3ce5f5bc"
owners = ["xorus","wozaiha"]
changelog = """\
- Fix decimals not being properly hidden with the display threshold option"""
