[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = '0d1a538976ff19fe82d88be43f894ffb894167bc'
owners = [ 'ascclemens', 'LittleNightmare' ]
project_path = 'csharp/RemotePartyFinder'
changelog = '支持国服，但服务器性能和可访问不保证'
