[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = 'ae1d2a3a82dfe61d3d255e441f392a8f6d2e4f74'
owners = [ 'lojewalo', 'LittleNightmare' ]
project_path = 'csharp/RemotePartyFinder'
changelog = 'API 9'
