[plugin]
repository = "https://github.com/Annullare/ffxiv-characterstatus-refined.git"
commit = "03d47f68432f1c22d95a4fce7daca809d474fd4c"
owners = [
    "Kouzukii",
    "Annullare",
]
project_path = "CharacterPanelRefined"
changelog = """
Disable the GCD support since it was causing crashes until the cause has been identified.
"""
