[plugin]
repository = "https://github.com/zhouhuichen741/ffxiv-characterstatus-refined.git"
commit = "550822107fc77a6437c144a850f5d10177d2dda8"
owners = ["Kouzukii",
          "zhouhuichen741"
]
project_path = "CharacterPanelRefined"
changelog = """
Fix ilvl sync being incorrectly displayed in bozja and eureka.
"""
