[plugin]
repository = "https://github.com/zhouhuichen741/ffxiv-characterstatus-refined.git"
commit = "e18119101121a6c5257b049ddb6cdd3a52e4f630"
owners = [
    "Kouzukii",
    "zhouhuichen741",
]
project_path = "CharacterPanelRefined"
changelog = """
Disable the GCD support since it was causing crashes until the cause has been identified.
"""
