[plugin]
repository = "https://github.com/zhouhuichen741/ffxiv-characterstatus-refined.git"
commit = "b62067831361c89427fdecfd60b689fc0c9a307a"
owners = [
          "Kouzukii",
          "zhouhuichen41"
         ]
project_path = "CharacterPanelRefined"
changelog = """
- 本地化
"""
