[plugin]
repository = "https://github.com/zhouhuichen741/ffxiv-characterstatus-refined.git"
commit = "8f12062091b5620817c60ea459bef9777c9ac85d"
owners = [
    "Kouzukii",
    "zhouhuichen741",
]
project_path = "CharacterPanelRefined"
changelog = """
Fixed a bug that had items being shown as Ilvl synced when they shouldn't be.
Fixed Shifu being assumed to be a 13% speed increase instead of 10% at level 70.
"""
