[plugin]
repository = "https://github.com/uiharuayako/OrchestrionPlugin.git"
commit = "ee3baccd1811065c99ee697d15d463b5709ce46b"
owners = [
    "lmcintyre",
    "uiharuayako"
]
project_path = "Orchestrion"
