[plugin]
repository = "https://github.com/uiharuayako/OrchestrionPlugin.git"
commit = "ff9c480bc4b15c9672d5068747725eb78b168567"
owners = [
    "lmcintyre",
    "uiharuayako"
]
project_path = "Orchestrion"
