[plugin]
repository = "https://github.com/cyf5119/WaymarkPresetPlugin.git"
commit = "52f9b8d7834d8c4307bcfa3e5dbb346eb1d98637"
owners = [
    "PunishedPineapple",
    "abashby",
    "Infiziert90",
    "cyf5119"
]
project_path = "WaymarkPresetPlugin"
changelog = '''
汉化。
'''
